Update OCP check script and upstream support with the prow changes
dora-metrics/pelorus pull request #1084
Opened 2023-10-13 16:17 UTC by mpryc

The PROW CI jobs were updated to use only latest OCP release for their runs. The documentation and the check openshift version script needs to be changed as well.

PROW PR: https://github.com/openshift/release/pull/44348

2023-10-13 16:28 UTC, mateusoliveira43 commented on scripts/check_openshift_version.py
> +OCP_CI_VERSION_URL = "https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/graph"
would change to `OCP_VERSIONS_URL`

2023-10-13 16:30 UTC, mateusoliveira43 commented on docs/UpstreamSupport.md
> +The Pelorus engineering team will provide **best-effort** level support for it on the currently latest released stable minor versions of the OpenShift version 4.
...stable minor **versions** of the... -> ...stable minor **version** of the...

2023-10-13 16:38 UTC, mateusoliveira43 requested changes
Also need to remove old references in README.md and .github/ISSUE_TEMPLATE/bug.yml

I would also add a deprecated warning (just a comment is enough) to Makefile E2E test scenario 2 command https://github.com/dora-metrics/pelorus/blob/master/Makefile#L126

2023-10-13 16:39 UTC, mateusoliveira43 commented
/hold
wait the other PR merge

2023-10-13 18:47 UTC, mpryc commented
/unhold

2023-10-13 18:47 UTC, mpryc commented
/retest-required

2023-10-16 13:34 UTC, mpryc commented
> Also need to remove old references in README.md and .github/ISSUE_TEMPLATE/bug.yml
> 
> I would also add a deprecated warning (just a comment is enough) to Makefile E2E test scenario 2 command https://github.com/dora-metrics/pelorus/blob/master/Makefile#L126

I left the issue list of older OCP releases. It's a bug entry and we don't force user to use X or Y version of OCP + we should allow to log against already existing deployments.

I don't think we should deprecate scenario-2, we just don't run them in the periodics.

2023-10-16 13:39 UTC, mateusoliveira43 approved these changes

2023-10-16 13:45 UTC, mateusoliveira43 commented
I think the regex for PROW is working, it did not trigger for your newest commit that does not touch the files delacred in it :smile: 

But I think we left this there https://github.com/openshift/release/blob/master/core-services/prow/02_config/dora-metrics/pelorus/_prowconfig.yaml#L19 we should remove it right? 

(if you want, you can bypass branch protection and merge this PR)

2023-10-16 14:00 UTC, mpryc commented
> I think the regex for PROW is working, it did not trigger for your newest commit that does not touch the files delacred in it 😄
> 
> But I think we left this there https://github.com/openshift/release/blob/master/core-services/prow/02_config/dora-metrics/pelorus/_prowconfig.yaml#L19 we should remove it right?
> 
> (if you want, you can bypass branch protection and merge this PR)

I think it's because my PR was after the above was merged, so it got old required jobs.

2023-10-17 10:57 UTC, mpryc commented
/test 4.13-e2e-openshift

2023-10-17 12:33 UTC, mpryc commented
Merging as it previously passed checks.

2023-10-17 12:33 UTC, merged