Rebuilding docs requirements tree to get the builds working again.
dora-metrics/pelorus pull request #1132
Opened 2024-05-09 19:41 UTC by etsauer

- [x] I have read [Pelorus Contributing guidelines](https://github.com/dora-metrics/pelorus/blob/master/CONTRIBUTING.md)

## Description

This PR pulls in updated versions of all the packages involved in building our docs with `mkdocs`. This should fix the broken builds on readthedocs.org

## Testing Instructions

1. Check the readthedocs CI check and make sure that it passes
2. Check the built docs site and make sure everything looks right

2024-05-10 14:07 UTC, mateusoliveira43 commented on pyproject.toml
>  [tool.poetry.group.doc.dependencies]
I would change less things here

From what I searched, here is the problem https://github.com/readthedocs/readthedocs.org/issues/11247

And here the solution https://github.com/squidfunk/mkdocs-material/releases/tag/9.5.16

So, I would try to only update `mkdocs-material`

To do so, run `poetry update mkdocs-material --with=doc`

This command will update 3 packages listed in `pyproject.toml`, manually update then here
```yaml
mkdocs = "^1.6.0"
...
mkdocs-material = "^9.5.21"
...
pymdown-extensions = "^10.4"
```

Then, run `make update-requirements`

2024-05-10 14:07 UTC, mateusoliveira43 requested changes
need to run `make update-requirements` and update `poetry.lock`

2024-05-14 14:16 UTC, etsauer commented
Ok, how's this look?

2024-08-22 13:33 UTC, etsauer commented
/retest

2024-08-22 13:38 UTC, closed without merging